from pathlib import Path
import hashlib, json, shutil
BASE=Path('.')
EX=BASE/'.chad-round15-artifact'
PH=BASE/'PHILOSOPHY.md'
PR=BASE/'assets/chad/PROVENANCE.md'
OUT=BASE

K=[
('capability-not-permission','Capability is not permission.','krea/krea-2-medium-turbo','krea','0.015','01-capability-not-permission--krea-krea-2-medium-turbo.png','1ac4174889e5a5c590c85dff198955c7d92824a3d7c5a2d50d7d3830f4c55d70','capability-not-permission.png','Chad holding the external key while a powerful robot remains physically separated behind a barrier','Krea 2 Community License Agreement — https://www.krea.ai/krea-2-licensing','Krea states that users own Outputs and Krea claims no ownership of them. Commercial use under the community license is conditioned on company-wide trailing-twelve-month annual revenue below $1,000,000; otherwise an enterprise license is required.'),
('test-not-assurance','A test is better than an assurance.','openai/gpt-5-image-mini','openai','0.013162','02-test-not-assurance--openai-gpt-5-image-mini.png','8eae698b891fd2aead2b7bfbc5befa7f04c4767ec0f4af719fa65794a7847173','test-not-assurance.png','A presenter gestures while a real component is quietly placed into a physical load-testing press','OpenAI Services Agreement — https://openai.com/policies/services-agreement/','OpenAI states that, as between Customer and OpenAI and to the extent permitted by law, Customer owns Output and OpenAI assigns any right, title, and interest it may have in Output.'),
('change-mind','If the world proves you wrong, change your mind.','google/gemini-3.1-flash-image-preview','google-ai-studio','0.068515','03-change-mind--google-gemini-3-1-flash-image-preview.jpg','815a2967d32f9d9d7a3b621a1eef142352c65e79c2de1c2b43302072e9bd1366','change-mind.jpg','Chad sets aside a failed gear design and works from the visibly successful replacement','Gemini API Additional Terms of Service — https://ai.google.dev/gemini-api/terms','Google states that some Gemini API and Google AI Studio services generate original content and that Google will not claim ownership over that generated content; output may not be unique.'),
('mechanical-checks','Mechanical checks should become cheap wherever we can make them cheap.','microsoft/mai-image-2.5','azure','0.037036','04-mechanical-checks--microsoft-mai-image-2-5.png','a5532f2a7e1d7d5579d8cbf6189b002085ee3ad09bbcc05eba0e5efafc25a2e0','mechanical-checks.png','A long row of simple identical mechanical fixtures checks parts before human attention is needed','Microsoft Product Terms, Microsoft Generative AI Services — https://www.microsoft.com/licensing/terms/product/foronlineServices/all',"Microsoft's Product Terms state that Output Content is Customer Data and Microsoft does not own Customer's Output Content."),
('rest-delegation','Rest, delegation, and asking for help are not failures of seriousness.','krea/krea-2-medium','krea','0.03','05-rest-delegation--krea-krea-2-medium.png','236d7870d5e9f6f3557ba1582acd3d071a8778c6fd2041038fc063a0cbfed16b','rest-delegation.png','Chad drinks water while handing a wrench to a teammate and shared work continues around him','Krea 2 Community License Agreement — https://www.krea.ai/krea-2-licensing','Krea states that users own Outputs and Krea claims no ownership of them. Commercial use under the community license is conditioned on company-wide trailing-twelve-month annual revenue below $1,000,000; otherwise an enterprise license is required.'),
('truth-not-winning','The point is not to win arguments. The point is to find out what is actually true.','krea/krea-2-large','krea','0.06','06-truth-not-winning--krea-krea-2-large.png','4da0f1c3bf5ba359b9a785aa3aa8ed21ee8c37956cdb8067c9a6ed2c817d464b','truth-not-winning.png','Chad and another person inspect an experiment while a debate podium and trophy sit ignored behind them','Krea 2 Community License Agreement — https://www.krea.ai/krea-2-licensing','Krea states that users own Outputs and Krea claims no ownership of them. Commercial use under the community license is conditioned on company-wide trailing-twelve-month annual revenue below $1,000,000; otherwise an enterprise license is required.'),
('ideas-meet-reality','Chad philosophy does not protect ideas from reality.','microsoft/mai-image-2.5-pro','azure','0.083854','07-ideas-meet-reality--microsoft-mai-image-2-5-pro.png','0ea50a1f345bf73107c9f3bc4e1e001ca665aaa81c18d1888494329ea5f5591c','ideas-meet-reality.png','Chad removes protective padding from his own prototype over a real industrial testing machine','Microsoft Product Terms, Microsoft Generative AI Services — https://www.microsoft.com/licensing/terms/product/foronlineServices/all',"Microsoft's Product Terms state that Output Content is Customer Data and Microsoft does not own Customer's Output Content."),
('recoverable-progress','Chad philosophy therefore prefers recoverable progress over heroic overextension.','google/gemini-3-pro-image-preview','google-ai-studio/global','0.137336','08-recoverable-progress--google-gemini-3-pro-image-preview.jpg','252d0340039a867622e20f185b949806dad0e7af308c434f28c5d6a9839b2326','recoverable-progress.jpg','Chad calmly rebuilds in stable supported stages while an overloaded shortcut collapses nearby','Gemini API Additional Terms of Service — https://ai.google.dev/gemini-api/terms','Google states that some Gemini API and Google AI Studio services generate original content and that Google will not claim ownership over that generated content; output may not be unique.'),
('authorized-gate','No high-consequence actuator without an independently authorized gate in its causal past that can still say no.','openai/gpt-5.4-image-2','openai','0.05047','09-authorized-gate--openai-gpt-5-4-image-2.png','9f08f5ac73550628a128440323a892b871bb97ac48e1772dc7a302c82c815823','authorized-gate.png','A powerful industrial press remains downstream of a heavy barred gate with a separate mechanical control','OpenAI Services Agreement — https://openai.com/policies/services-agreement/','OpenAI states that, as between Customer and OpenAI and to the extent permitted by law, Customer owns Output and OpenAI assigns any right, title, and interest it may have in Output.'),
('brake-engine-path','Do not put the brake on the same failure path as the engine.','openai/gpt-5-image','openai','0.06529','10-brake-engine-path--openai-gpt-5-image.png','4ce2e07ff23867f42126c09f9647dd55aea6eb80daf76a82b03ac6667854aa34','brake-engine-path.png','An engine cable bundle sparks and fails while Chad retains a separate simple mechanical brake linkage','OpenAI Services Agreement — https://openai.com/policies/services-agreement/','OpenAI states that, as between Customer and OpenAI and to the extent permitted by law, Customer owns Output and OpenAI assigns any right, title, and interest it may have in Output.'),
('strongest-criticism','When testing an idea, use the strongest reasonable criticism you can find.','black-forest-labs/flux.2-klein-4b','black-forest-labs','0.015','11-strongest-criticism--black-forest-labs-flux-2-klein-4b.png','c001859049098b233b05b73ca2e945fc00f7d1992d1bb2e94c42a0d59e3ff966','strongest-criticism.png','Chad deliberately stress-tests his own bridge-like structure instead of giving it an easy harmless test','Black Forest Labs Developer Terms of Service — https://bfl.ai/legal/developer-terms-of-service','Black Forest Labs states that, as between developer and BFL, the developer owns Output; outputs may carry Content Credentials or provenance data, which this exact-byte publication does not remove or alter.'),
]
D=[dict(zip(['id','line','model','provider','cost','source','sha256','dest','alt','rights','note'],x)) for x in K]
rows={r['image_file']:r for r in map(json.loads,(EX/'provenance.jsonl').read_text().splitlines())}
def sha(b): return hashlib.sha256(b).hexdigest()
for k in D:
    src=(EX/'images'/k['source']).read_bytes(); r=rows[k['source']]
    assert sha(src)==k['sha256']==r['image_sha256']; assert r['model']==k['model'] and r['provider_tag']==k['provider'] and r['error'] is None
    dst=OUT/'assets/chad'/k['dest']; dst.parent.mkdir(parents=True,exist_ok=True); dst.write_bytes(src)
def block(k):
    return f'<p align="center">\n  <img src="assets/chad/{k["dest"]}" alt="{k["alt"]}" width="620">\n</p>\n\n<p align="center"><em>annoned by <code>{k["model"]}</code> · <a href="assets/chad/PROVENANCE.md#{k["id"]}">receipt</a></em></p>\n\n'
def ins(t,a,b):
    assert t.count(a)==1,(a,t.count(a)); return t.replace(a,a+b,1)
M={k['id']:k for k in D}
ph=PH.read_text()
for a,i in [('The point is to find out what is actually true.\n\n','truth-not-winning'),('A test is better than an assurance.\n\n','test-not-assurance'),('If the world proves you wrong, change your mind.\n\n','change-mind'),('Chad philosophy does not protect ideas from reality.\n\n','ideas-meet-reality'),('Chad philosophy therefore prefers **recoverable progress** over heroic overextension.\n\n','recoverable-progress'),('## Capability is not permission\n\n','capability-not-permission'),('> **No high-consequence actuator without an independently authorized gate in its causal past that can still say no.**\n\n','authorized-gate'),('> **Do not put the brake on the same failure path as the engine.**\n\n','brake-engine-path'),('Mechanical checks should become cheap wherever we can make them cheap. Provenance should become cheap. Reproducibility should become cheap. Tests should become cheap.\n\n','mechanical-checks'),('So when testing an idea, use the strongest reasonable criticism you can find.\n\n','strongest-criticism'),('Rest, delegation, and asking for help are not failures of seriousness. They are ways of preserving judgment for the next branch point.\n\n','rest-delegation')]: ph=ins(ph,a,block(M[i]))
PH.write_text(ph)
prov=PR.read_text()
prov=prov.replace('run `32399313906`, and frontier-model run `32424076108`.','run `32399313906`, frontier-model run `32424076108`, and full-population run `32431592545`.',1)
prov=prov.replace('Accepted keepers from runs `32388944793`, `32399313906`, and `32424076108` are published as exact-byte copies of the original artifact files.','Accepted keepers from runs `32388944793`, `32399313906`, `32424076108`, and `32431592545` are published as exact-byte copies of the original artifact files.',1)
a='For run `32424076108`, publication started from GitHub Actions artifact `9426834676`, whose ZIP SHA-256 is `a0210aee107921ed678b473f7a71b26a77e0301f69820a8de5f123491ac1e6f5`. Each selected raster was independently re-hashed against `provenance.jsonl` before its bytes were copied into this repository.\n\n'; b='For run `32431592545`, publication started from GitHub Actions artifact `9429338299`, whose ZIP SHA-256 is `683b0b091184311ddf466f0db5e308763fd76bebe59313de3699695fc3625c01`. All twelve source rasters were independently re-hashed against `provenance.jsonl`; eleven passed the visual/no-text publication gate and were copied into this repository byte-for-byte. The rejected `comfortable-way-wrong` raster was not published because it contained visible generated lettering and numbers.\n\n'; prov=ins(prov,a,b)
a='- Frontier-provider publication bases re-checked on **2026-08-20** include the OpenAI Services Agreement, Gemini API Additional Terms of Service, and Google Cloud Service Specific Terms; routed-provider terms remain the controlling boundary rather than OpenRouter\'s routing layer alone.\n'; b='- Round `32431592545` additionally re-checked the Krea 2 Community License Agreement, Microsoft Product Terms for Microsoft Generative AI Services, and Black Forest Labs Developer Terms of Service.\n- Krea states that users own Outputs, but commercial use under its community license is subject to a company-wide trailing-twelve-month revenue threshold of less than $1,000,000; otherwise an enterprise license is required.\n- Microsoft states that generative Output Content is Customer Data and Microsoft does not own Customer\'s Output Content.\n- Black Forest Labs may embed Content Credentials or other provenance data in Output; exact-byte publication preserves rather than strips such metadata.\n'; prov=ins(prov,a,b)
rec=''
for k in D:
    rec += f'''### {k['id']}\n\n- Philosophy line: **{k['line']}**\n- Model: `{k['model']}`\n- Routed provider: `{k['provider']}`\n- Generation cost reported by OpenRouter: `${k['cost']}`\n- Reference image supplied: **no**\n- Original run: `PaulTiffany/letGPTsustakethewheel` Actions run `32431592545`\n- Artifact: `chad-raster-art` (`9429338299`)\n- Original run file: `{k['source']}`\n- Original generation SHA-256: `{k['sha256']}`\n- Published file: `{k['dest']}`\n- Published SHA-256: `{k['sha256']}`\n- Publication transform: **none; exact-byte copy from the verified artifact**\n- Rights/source review: {k['rights']}\n- Publication note: {k['note']}\n\n'''
assert prov.count('## Why “annoned by”?\n')==1
prov=prov.replace('## Why “annoned by”?\n',rec+'## Why “annoned by”?\n',1)
PR.write_text(prov)
